#!/usr/bin/env bash
set -euo pipefail

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

fake_root="$workdir/root"
pkgdir="$workdir/pkg/kernel-6.19.12"
mkdir -p "$fake_root/etc/default" "$fake_root/boot/grub" "$workdir/bin" "$workdir/repo/kernel" "$pkgdir/boot"
mkdir -p "$workdir/repo/1.0/packages/grub-bios-2.12" "$workdir/repo/1.0/packages/grub-efi-2.12"
cat > "$fake_root/etc/os-release" <<'EOF'
ID=AdavaLinux
VERSION=1.0
EOF
cat > "$fake_root/etc/default/grub" <<'EOF'
GRUB_CMDLINE_LINUX="root=/dev/vda1 nomodeset legacy=1"
GRUB_CMDLINE_LINUX_DEFAULT="legacy"
EOF
mkdir -p "$fake_root/var/lib/syspckg/installed"
mkdir -p "$fake_root/usr/etc/grub.d"
printf '#!/bin/sh\n' > "$fake_root/usr/etc/grub.d/10_linux"
printf '#!/bin/sh\n' > "$fake_root/usr/etc/grub.d/20_linux_xen"
chmod +x "$fake_root/usr/etc/grub.d/10_linux" "$fake_root/usr/etc/grub.d/20_linux_xen"
printf 'old kernel\n' > "$fake_root/boot/vmlinuz-6.19.11"
printf 'old initrd\n' > "$fake_root/boot/initramfs-disk-6.19.11.gz"
cat > "$fake_root/boot/grub/grub.cfg" <<'EOF'
set timeout=10
menuentry "AdavaLinux old" {
	linux /boot/vmlinuz-6.19.11 root=/dev/vda1 rootwait rw console=tty1
	initrd /boot/initramfs-disk.gz
}
EOF

cat > "$pkgdir/syspckg-info" <<'EOF'
PKG_VERSION=6.19.12
ID=AdavaLinux
VERSION=1.0
EOF
printf 'new kernel\n' > "$pkgdir/boot/vmlinuz-6.19.12"
printf 'new initrd\n' > "$pkgdir/boot/initramfs-disk-6.19.12.gz"
( cd "$workdir/pkg" && tar -cJf "$workdir/repo/kernel/kernel-6.19.12.syspckg" kernel-6.19.12 )
cat > "$workdir/repo/1.0/packages/grub-bios-2.12/syspckg-info" <<'EOF'
PKG_VERSION=2.12
ID=AdavaLinux
VERSION=1.0
EOF
mkdir -p "$workdir/repo/1.0/packages/grub-bios-2.12/usr/sbin"
printf '#!/bin/sh\n' > "$workdir/repo/1.0/packages/grub-bios-2.12/usr/sbin/grub-mkconfig"
( cd "$workdir/repo/1.0/packages" && tar -cJf grub-bios-2.12.syspckg grub-bios-2.12 )
cat > "$workdir/repo/1.0/packages/grub-efi-2.12/syspckg-info" <<'EOF'
PKG_VERSION=2.12
ID=AdavaLinux
VERSION=1.0
EOF
( cd "$workdir/repo/1.0/packages" && tar -cJf grub-efi-2.12.syspckg grub-efi-2.12 )

cat > "$workdir/bin/wget" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

if [ "${1:-}" = "-qO-" ]; then
  case "$2" in
    */kernel/)
      printf '<a href="kernel-6.19.12.syspckg">kernel-6.19.12.syspckg</a>\n'
      ;;
    */1.0/packages/)
      printf '<a href="grub-bios-2.12.syspckg">grub-bios-2.12.syspckg</a>\n'
      printf '<a href="grub-efi-2.12.syspckg">grub-efi-2.12.syspckg</a>\n'
      ;;
  esac
  exit 0
fi
if [ "${1:-}" = "-O" ]; then
  case "$3" in
    */kernel/kernel-6.19.12.syspckg)
      cp "$TEST_REPO/kernel/kernel-6.19.12.syspckg" "$2"
      ;;
    */1.0/packages/grub-bios-2.12.syspckg)
      cp "$TEST_REPO/1.0/packages/grub-bios-2.12.syspckg" "$2"
      ;;
    */1.0/packages/grub-efi-2.12.syspckg)
      cp "$TEST_REPO/1.0/packages/grub-efi-2.12.syspckg" "$2"
      ;;
    *)
      exit 1
      ;;
  esac
  exit 0
fi
exit 1
EOF
chmod +x "$workdir/bin/wget"

cat > "$workdir/bin/chroot" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >> "$TEST_CHROOT_LOG"
if [ "$2" = "/usr/sbin/grub-mkconfig" ] && [ "$3" = "-o" ]; then
  mkdir -p "$1/boot/grub"
  printf 'generated by grub-mkconfig\n' > "$1$4"
  exit 0
fi
exit 1
EOF
chmod +x "$workdir/bin/chroot"

cat > "$workdir/syspckg-source" <<'EOF'
SOURCE_URL=http://example.invalid/products/AdavaLinux
EOF

gcc -D_GNU_SOURCE -std=c11 -Wall -Wextra -DSYSPCKG_SOURCE_FILE='"'"$workdir/syspckg-source"'"' \
  main.c -o "$workdir/syspckg"

PATH="$workdir/bin:$PATH" TEST_REPO="$workdir/repo" \
  TEST_CHROOT_LOG="$workdir/chroot.log" \
  "$workdir/syspckg" update --kernel --root "$fake_root" --allow-root -y >/dev/null

[ "$(readlink "$fake_root/boot/vmlinuz")" = "vmlinuz-6.19.12" ]
[ "$(readlink "$fake_root/boot/initramfs-disk.gz")" = "initramfs-disk-6.19.12.gz" ]
grep -q '^/.*root /usr/sbin/grub-mkconfig -o /boot/grub/grub.cfg$' "$workdir/chroot.log"
grep -q 'generated by grub-mkconfig' "$fake_root/boot/grub/grub.cfg"
[ -f "$fake_root/var/lib/syspckg/installed/grub-bios-2.12.list" ]
[ ! -x "$fake_root/usr/etc/grub.d/10_linux" ]
[ ! -x "$fake_root/usr/etc/grub.d/20_linux_xen" ]
expected_grub=$(cat <<'EOF'
GRUB_TIMEOUT=10
GRUB_DEFAULT=0
GRUB_CMDLINE_LINUX="root=/dev/vda1 rootfstype=ext4 rootwait rootdelay=5 rw console=ttyS0 console=tty1 libata.force=noncq"
GRUB_CMDLINE_LINUX_DEFAULT="quiet"
EOF
)
[ "$(cat "$fake_root/etc/default/grub")" = "$expected_grub" ]
! grep -q 'nomodeset\|legacy=1' "$fake_root/etc/default/grub"

printf 'update kernel boot tests passed\n'
